plugins {
    id 'java'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = project.mod_version
group = project.mod_group

base {
    archivesName = "${project.mod_id}-neoforge-${project.minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

neoForge {
    version = project.neoforge_version

    accessTransformers.from('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

var replaceProperties = [
        mod_id           : project.mod_id,
        mod_name         : project.mod_name,
        mod_version      : project.mod_version,
        minecraft_version: project.minecraft_version,
        neoforge_version : project.neoforge_version,
]

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
    validateDistributionUrl = false
}

tasks.named('processResources', ProcessResources).configure {
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}
